### ISSUE TITLE
Missing scope in footer.html

### ISSUE THREAD

**Issue by cowboysmall** [MeiK2333/github-style#1]
Hi,

love your theme. 

I noticed an issue - in footer.html there is a missing scope in the partial function invocation - at line 27:

```
{{ partial "script.html" }}
```

should be:

```
{{ partial "script.html" . }}
```
Thanks,

J.K.

**Comment by MeiK2333** [comment]
Thank you very much for your issue, I have fixed it.

**Comment by cowboysmall** [comment]
No problem. Pleasure. And thanks for the theme!
