### ISSUE TITLE
页尾如何设置？

### ISSUE THREAD

**Issue by xijaja** [MeiK2333/github-style#110]
您好，我是一个新手。
我特别喜欢这个风格，有种以假乱真的感觉，特帅！
在国内，所有的网站都需要备案，并且要在页面底部显示备案号并且要能够跳转到工信部的网站。
我不晓得，这应该如何设置，我应该怎么做？

**Comment by MeiK2333** [comment]
通过 Copyright 配置可以自定义底部内容

**Comment by xiwuou** [comment]
非常感谢
