### ISSUE TITLE
能够支持标签分栏的功能吗

### ISSUE THREAD

**Issue by rainofsilence** [MeiK2333/github-style#119]
我想将文章打上不同的标签能够在不同的标签目录下展示要怎么做呢

**Comment by kurt-liao** [comment]
1. Add tags property in your post markdown file.
![2022-09-01_10-12](https://user-images.githubusercontent.com/32745146/187817606-016656ea-9949-448f-92c9-d89caa6b9132.png)

2. In home page, you can see tags display in every post.
![2022-09-01_11-22](https://user-images.githubusercontent.com/32745146/187826307-b805acf7-a56b-4df7-a794-bfb2f7153947.png)

3. In posts page, you can see a tag list on the top of post list.
![2022-09-01_11-23](https://user-images.githubusercontent.com/32745146/187826319-74025cb5-ea41-4cb5-a364-cbb15660b9de.png)

4. And you can click on the tag for filtering.
![2022-09-01_11-34](https://user-images.githubusercontent.com/32745146/187826343-cec06c6c-2ea8-4045-9a3d-804d256aca6b.png)


Take a look and try it on my site: https://kurt-liao.github.io/

>BTW, you may confused about some features that is not in this repo, that's because I used built the theme that fork from this and support additional features.
> For more information, feel free to take a look at my fork version: https://github.com/kurt-liao/github-style-plus

**Comment by rainofsilence** [comment]
Thank you, @kurt-liao. I'll give it a try.
