### ISSUE TITLE
Using Date instead of PublishedDate

### ISSUE THREAD

**Issue by PiroHiroPiro** [MeiK2333/github-style#16]
I feel strange that PublishDate is used for both Created date (line 25 in post.html) and Updated date (line 47 in overview.html and lines 43 in posts.html).

One solution is to change the PublishedDate on line 25 of post.html to Date.

I hope you will consider this issue. 
Thank you.

**Comment by MeiK2333** [comment]
fixed

**Comment by PiroHiroPiro** [comment]
Thank you!
