### ISSUE TITLE
Request for Dark Mode

### ISSUE THREAD

**Issue by natkingchloe** [MeiK2333/github-style#27]
I really like this theme and have been applied for my personal site, are you considering to implement dark mode?

**Comment by MeiK2333** [comment]
Of course, I'll be working with @dreamerblue  on this.

**Comment by natkingchloe** [comment]
great!  I'll look forward to the update, by the way, thank you!

**Comment by MeiK2333** [comment]
@natkingchloe close for https://github.com/MeiK2333/github-style/pull/28

![image](https://user-images.githubusercontent.com/20951666/81063453-6549c600-8f0a-11ea-8ccc-a3bb231126f2.png)
![image](https://user-images.githubusercontent.com/20951666/81063492-77c3ff80-8f0a-11ea-9590-c2d3655d429b.png)
