### ISSUE TITLE
it doesn't work in chrome or firfox

### ISSUE THREAD

**Issue by zxmrlc** [MeiK2333/github-style#3]
Thanks for your theme!
I find some problems with web-security.
Chrome will intercept  and prompt a message "loaded unsafe script".
![request](https://user-images.githubusercontent.com/24544360/69213492-38456900-0b9f-11ea-9a8c-96b77923d0df.png)

**Comment by blue-bird1** [comment]
Because the author converted the script path to an absolute path. So in fact the protocol uses the baseurl in config.toml. This problem will occur if you fill in http://xxx and your deployed domain name is https

**Comment by zxmrlc** [comment]
> Because the author converted the script path to an absolute path. So in fact the protocol uses the baseurl in config.toml. This problem will occur if the baseurl you filled in is http://xxx and the domain you are deploying is https

First,thanks for your answer.
but I am afraid that http/https doesn't  applicable to this issue.
*baseURL = "http://zxmrlc.github.io/"*  are used for site "http://zxmrlc.github.io/".

**Comment by zxmrlc** [comment]
After I changed HTTP to HTTPS, the problem has been solved!
I take this opportunity to thank you again for [blue-bird1's answer](https://github.com/MeiK2333/github-style/issues/3#issuecomment-555862300)
