### ISSUE TITLE
SVG icon appears collapsed

### ISSUE THREAD

**Issue by ress997** [MeiK2333/github-style#5]
github icon breaks when built using `--minify`

![Screenshot 2019-11-21 at 23 14 51](https://user-images.githubusercontent.com/48500247/69345636-c52e1680-0cb4-11ea-9cde-ac853e4590f9.png)
![Screenshot 2019-11-21 at 23 14 57](https://user-images.githubusercontent.com/48500247/69345638-c52e1680-0cb4-11ea-9f41-5d3bb549399a.png)

**Comment by MeiK2333** [comment]
It looks like this Issue: https://github.com/gohugoio/hugo/issues/6475

The minify library has fixed this issue: https://github.com/tdewolff/minify/issues/269, but hugo has not introduced the latest changes.

**Comment by ress997** [comment]
Thank you for telling me.

I am waiting for the latest Hugo release.

**Comment by ress997** [comment]
Fixed https://github.com/gohugoio/hugo/releases/tag/v0.60.1
