### ISSUE TITLE
Feature Request: Emoji

### ISSUE THREAD

**Issue by ress997** [MeiK2333/github-style#74]
You can see emojis on your GitHub profile page. I thought it would be cute to express it with pictograms and I wanted it to be implemented.
![image](https://user-images.githubusercontent.com/48500247/131946341-e00e0b2a-8a62-405b-98fd-fc6ec8e61c66.png)

**Comment by MeiK2333** [comment]
https://github.com/MeiK2333/github-style/blob/master/config.template.toml#L25
