### ISSUE TITLE
Display the Contribution Graph

### ISSUE THREAD

**Issue by ress997** [MeiK2333/github-style#8]
I want the contribution graph displayed on GitHub to be displayed on the top page.

I think it is possible if you use https://github.com/a-know/grass-graph

**Comment by ress997** [comment]
I am checking to see if I can use it for the creator of the grass-graph.
https://github.com/a-know/grass-graph/issues/30

**Comment by MeiK2333** [comment]
Interesting ideas! I will consider this features of soon.

**Comment by MeiK2333** [comment]
Hello, I updated the posts graph and I personally feel this way is better than the contribution graph.

If you have a better idea, you're welcome to bring it up too.

![image](https://user-images.githubusercontent.com/20951666/81636661-fa871600-9446-11ea-9b9c-f2e56a1f262e.png)
![image](https://user-images.githubusercontent.com/20951666/81636693-0ffc4000-9447-11ea-984b-63b77c75aea4.png)

**Comment by ress997** [comment]
I thought it would be sad not to see anything, so I suggested it.
I think it's a good idea to show a list of posts.
