### ISSUE TITLE
Fatal error when installing theme

### ISSUE THREAD

**Issue by ThomasRettig** [MeiK2333/github-style#81]
After typing in the below command,
``` C:\Users\frede\Downloads\notepadium>git submodule add https://github.com/MeiK2333/github-style.git ```
I get this:
``` fatal: not a git repository (or any of the parent directories): .git ```

I am following the ``` README.md ``` documentation from this repository word-for-word. Is this a bug? I do not encounter this error when installing other themes. My OS is Windows11.

**Comment by ChobobDev** [comment]
did you git init from the first hand?

**Comment by ThomasRettig** [comment]
> did you git init from the first hand?
 After running git init, the installation now works. Thanks for your help! :bowtie:
